-- PUBLIC.BATCH_JOB_EXECUTION_SEQ definition

-- Drop table

-- DROP TABLE PUBLIC.BATCH_JOB_EXECUTION_SEQ;

CREATE TABLE PUBLIC.BATCH_JOB_EXECUTION_SEQ (
	ID BIGINT NOT NULL
);


-- PUBLIC.BATCH_JOB_INSTANCE definition

-- Drop table

-- DROP TABLE PUBLIC.BATCH_JOB_INSTANCE;

CREATE TABLE PUBLIC.BATCH_JOB_INSTANCE (
	JOB_INSTANCE_ID BIGINT NOT NULL,
	VERSION BIGINT,
	JOB_NAME CHARACTER VARYING(100) NOT NULL,
	JOB_KEY CHARACTER VARYING(32) NOT NULL,
	CONSTRAINT CONSTRAINT_3 PRIMARY KEY (JOB_INSTANCE_ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_3 ON PUBLIC.BATCH_JOB_INSTANCE (JOB_INSTANCE_ID);


-- PUBLIC.BATCH_JOB_SEQ definition

-- Drop table

-- DROP TABLE PUBLIC.BATCH_JOB_SEQ;

CREATE TABLE PUBLIC.BATCH_JOB_SEQ (
	ID BIGINT NOT NULL
);


-- PUBLIC.BATCH_STEP_EXECUTION_SEQ definition

-- Drop table

-- DROP TABLE PUBLIC.BATCH_STEP_EXECUTION_SEQ;

CREATE TABLE PUBLIC.BATCH_STEP_EXECUTION_SEQ (
	ID BIGINT NOT NULL
);


-- PUBLIC.EMPLOYEE definition

-- Drop table

-- DROP TABLE PUBLIC.EMPLOYEE;

CREATE TABLE PUBLIC.EMPLOYEE (
	ID BIGINT NOT NULL,
	NAME CHARACTER VARYING(255),
	"ROLE" CHARACTER VARYING(255),
	CONSTRAINT CONSTRAINT_7 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_7 ON PUBLIC.EMPLOYEE (ID);


-- PUBLIC.EMPLOYEE_PERFORMANCE definition

-- Drop table

-- DROP TABLE PUBLIC.EMPLOYEE_PERFORMANCE;

CREATE TABLE PUBLIC.EMPLOYEE_PERFORMANCE (
	ID BIGINT NOT NULL,
	NAME CHARACTER VARYING(255),
	"ROLE" CHARACTER VARYING(255),
	CONSTRAINT CONSTRAINT_B PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_B ON PUBLIC.EMPLOYEE_PERFORMANCE (ID);


-- PUBLIC.BATCH_JOB_EXECUTION definition

-- Drop table

-- DROP TABLE PUBLIC.BATCH_JOB_EXECUTION;

CREATE TABLE PUBLIC.BATCH_JOB_EXECUTION (
	JOB_EXECUTION_ID BIGINT NOT NULL,
	VERSION BIGINT,
	JOB_INSTANCE_ID BIGINT NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	START_TIME TIMESTAMP DEFAULT NULL,
	END_TIME TIMESTAMP DEFAULT NULL,
	STATUS CHARACTER VARYING(10),
	EXIT_CODE CHARACTER VARYING(20),
	EXIT_MESSAGE CHARACTER VARYING(2500),
	LAST_UPDATED TIMESTAMP,
	CONSTRAINT CONSTRAINT_4 PRIMARY KEY (JOB_EXECUTION_ID),
	CONSTRAINT JOB_INSTANCE_EXECUTION_FK PRIMARY KEY (JOB_INSTANCE_ID,JOB_INSTANCE_ID),
	CONSTRAINT JOB_INSTANCE_EXECUTION_FK FOREIGN KEY (JOB_INSTANCE_ID) REFERENCES PUBLIC.BATCH_JOB_INSTANCE(JOB_INSTANCE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX JOB_INSTANCE_EXECUTION_FK_INDEX_4 ON PUBLIC.BATCH_JOB_EXECUTION (JOB_INSTANCE_ID);
CREATE UNIQUE INDEX PRIMARY_KEY_4 ON PUBLIC.BATCH_JOB_EXECUTION (JOB_EXECUTION_ID);


-- PUBLIC.BATCH_JOB_EXECUTION_CONTEXT definition

-- Drop table

-- DROP TABLE PUBLIC.BATCH_JOB_EXECUTION_CONTEXT;

CREATE TABLE PUBLIC.BATCH_JOB_EXECUTION_CONTEXT (
	JOB_EXECUTION_ID BIGINT NOT NULL,
	SHORT_CONTEXT CHARACTER VARYING(2500) NOT NULL,
	SERIALIZED_CONTEXT CHARACTER LARGE OBJECT,
	CONSTRAINT CONSTRAINT_BD PRIMARY KEY (JOB_EXECUTION_ID),
	CONSTRAINT JOB_EXEC_CTX_FK PRIMARY KEY (JOB_EXECUTION_ID,JOB_EXECUTION_ID),
	CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES PUBLIC.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE UNIQUE INDEX PRIMARY_KEY_BD ON PUBLIC.BATCH_JOB_EXECUTION_CONTEXT (JOB_EXECUTION_ID);


-- PUBLIC.BATCH_JOB_EXECUTION_PARAMS definition

-- Drop table

-- DROP TABLE PUBLIC.BATCH_JOB_EXECUTION_PARAMS;

CREATE TABLE PUBLIC.BATCH_JOB_EXECUTION_PARAMS (
	JOB_EXECUTION_ID BIGINT NOT NULL,
	PARAMETER_NAME CHARACTER VARYING(100) NOT NULL,
	PARAMETER_TYPE CHARACTER VARYING(100) NOT NULL,
	PARAMETER_VALUE CHARACTER VARYING(2500),
	IDENTIFYING CHARACTER(1) NOT NULL,
	CONSTRAINT JOB_EXEC_PARAMS_FK PRIMARY KEY (JOB_EXECUTION_ID,JOB_EXECUTION_ID),
	CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES PUBLIC.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX JOB_EXEC_PARAMS_FK_INDEX_5 ON PUBLIC.BATCH_JOB_EXECUTION_PARAMS (JOB_EXECUTION_ID);


-- PUBLIC.BATCH_STEP_EXECUTION definition

-- Drop table

-- DROP TABLE PUBLIC.BATCH_STEP_EXECUTION;

CREATE TABLE PUBLIC.BATCH_STEP_EXECUTION (
	STEP_EXECUTION_ID BIGINT NOT NULL,
	VERSION BIGINT NOT NULL,
	STEP_NAME CHARACTER VARYING(100) NOT NULL,
	JOB_EXECUTION_ID BIGINT NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	START_TIME TIMESTAMP DEFAULT NULL,
	END_TIME TIMESTAMP DEFAULT NULL,
	STATUS CHARACTER VARYING(10),
	COMMIT_COUNT BIGINT,
	READ_COUNT BIGINT,
	FILTER_COUNT BIGINT,
	WRITE_COUNT BIGINT,
	READ_SKIP_COUNT BIGINT,
	WRITE_SKIP_COUNT BIGINT,
	PROCESS_SKIP_COUNT BIGINT,
	ROLLBACK_COUNT BIGINT,
	EXIT_CODE CHARACTER VARYING(20),
	EXIT_MESSAGE CHARACTER VARYING(2500),
	LAST_UPDATED TIMESTAMP,
	CONSTRAINT CONSTRAINT_7A PRIMARY KEY (STEP_EXECUTION_ID),
	CONSTRAINT JOB_EXECUTION_STEP_FK PRIMARY KEY (JOB_EXECUTION_ID,JOB_EXECUTION_ID),
	CONSTRAINT JOB_EXECUTION_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES PUBLIC.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX JOB_EXECUTION_STEP_FK_INDEX_7 ON PUBLIC.BATCH_STEP_EXECUTION (JOB_EXECUTION_ID);
CREATE UNIQUE INDEX PRIMARY_KEY_7A ON PUBLIC.BATCH_STEP_EXECUTION (STEP_EXECUTION_ID);


-- PUBLIC.BATCH_STEP_EXECUTION_CONTEXT definition

-- Drop table

-- DROP TABLE PUBLIC.BATCH_STEP_EXECUTION_CONTEXT;

CREATE TABLE PUBLIC.BATCH_STEP_EXECUTION_CONTEXT (
	STEP_EXECUTION_ID BIGINT NOT NULL,
	SHORT_CONTEXT CHARACTER VARYING(2500) NOT NULL,
	SERIALIZED_CONTEXT CHARACTER LARGE OBJECT,
	CONSTRAINT CONSTRAINT_E PRIMARY KEY (STEP_EXECUTION_ID),
	CONSTRAINT STEP_EXEC_CTX_FK PRIMARY KEY (STEP_EXECUTION_ID,STEP_EXECUTION_ID),
	CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID) REFERENCES PUBLIC.BATCH_STEP_EXECUTION(STEP_EXECUTION_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE UNIQUE INDEX PRIMARY_KEY_E ON PUBLIC.BATCH_STEP_EXECUTION_CONTEXT (STEP_EXECUTION_ID);